import telebot
from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton, ReplyKeyboardMarkup, KeyboardButton
import sqlite3
import os
import time
import threading
import shutil
from datetime import datetime
import markdown2
from fpdf import FPDF, HTMLMixin

class PDF(FPDF, HTMLMixin):
    def header(self):
        # Draw top accent bar
        self.set_fill_color(30, 41, 59) # Slate 800
        self.rect(0, 0, 210, 15, 'F')
        
        self.set_font('helvetica', 'B', 12)
        self.set_text_color(255, 255, 255)
        self.set_xy(15, 5)
        self.cell(0, 5, 'OFFICIAL STUDENT DOSSIER', 0, 1, 'L')
        
        self.set_text_color(30, 41, 59)
        self.ln(10)

    def footer(self):
        self.set_y(-20)
        self.set_draw_color(226, 232, 240) # Slate 200
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(5)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(100, 116, 139) # Slate 500
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Attendance Management Bot on {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

# Resolve database path (Updated for bot/ subdirectory)
DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'database', 'attendance.db')

# State management for announcements and orders
user_states_lock = threading.Lock()
user_states = {} # {user_id: {'state': 'idle', 'msg_id': None, 'msg_ids': [], 'timer': None}}

def get_settings():
    if not os.path.exists(DB_PATH):
        return None, None, None, "OFFICIAL STORE", None
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("SELECT telegram_bot_token, telegram_group_id, admin_telegram_id, store_name, birthday_image FROM settings LIMIT 1")
        row = cursor.fetchone()
        conn.close()
        if row:
            return row[0], row[1], row[2], row[3], row[4]
    except Exception as e:
        print(f"Error reading settings: {e}")
    return None, None, None, "OFFICIAL STORE", None

def find_students(query):
    """Finds students matching name or QR code and returns a list."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    # Search for matches
    cursor.execute("SELECT qr_code, name, course FROM users WHERE qr_code = ? OR name LIKE ? LIMIT 6", (query, f"%{query}%"))
    results = cursor.fetchall()
    conn.close()
    return results

def get_all_active_students():
    """Fetches all students who are not deleted."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT qr_code, name FROM users WHERE deleted_at IS NULL")
    results = cursor.fetchall()
    conn.close()
    return results

def get_student_stats(qr_code):
    """Fetches full attendance statistics for a specific student, filtered by active school year."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Base user info
    cursor.execute("SELECT qr_code, name, course FROM users WHERE qr_code = ? LIMIT 1", (qr_code,))
    user = cursor.fetchone()
    if not user:
        conn.close()
        return None
        
    qr_code, name, course = user
    
    # Retrieve active school year and normalize
    cursor.execute("SELECT active_school_year FROM settings LIMIT 1")
    setting_row = cursor.fetchone()
    active_sy = setting_row[0].strip() if (setting_row and setting_row[0]) else "SY 2024-2025"
    normalized_sy = active_sy.replace("SY ", "").replace("sy ", "").strip()
    
    # Aggregated Stats for Overall Summary
    # 1. Subject Attendance Stats (filtered by active school year)
    cursor.execute("""
        SELECT SUM(sa.status = 'present'), SUM(sa.status = 'late'), SUM(sa.status = 'absent')
        FROM subject_attendance sa
        JOIN subjects s ON sa.subject_id = s.id
        WHERE sa.qr_code = ? AND REPLACE(REPLACE(s.school_year, 'SY ', ''), 'sy ', '') = ?
    """, (qr_code, normalized_sy))
    s_stats = cursor.fetchone()
    
    # 2. Daily Event Stats (from attendance table with session, filtered by active school year)
    cursor.execute("""
        SELECT SUM(status = 'present'), SUM(status = 'late'), SUM(status = 'absent')
        FROM attendance 
        WHERE qr_code = ? AND (session IS NOT NULL AND session != '')
          AND REPLACE(REPLACE(school_year, 'SY ', ''), 'sy ', '') = ?
    """, (qr_code, normalized_sy))
    d_stats = cursor.fetchone()
    
    p = (s_stats[0] or 0) + (d_stats[0] or 0)
    l = (s_stats[1] or 0) + (d_stats[1] or 0)
    a = (s_stats[2] or 0) + (d_stats[2] or 0)
    
    # Get Records for Breakdown
    # 1. Subject Records (filtered by active school year)
    cursor.execute("""
        SELECT s.name, 
            SUM(sa.status = 'present'), SUM(sa.status = 'late'), SUM(sa.status = 'absent'),
            s.category
        FROM subject_attendance sa
        JOIN subjects s ON sa.subject_id = s.id
        WHERE sa.qr_code = ? AND REPLACE(REPLACE(s.school_year, 'SY ', ''), 'sy ', '') = ?
        GROUP BY s.id
    """, (qr_code, normalized_sy))
    subject_contexts = cursor.fetchall()
    
    # 2. Daily Event Records (filtered by active school year)
    cursor.execute("""
        SELECT session, SUM(status = 'present'), SUM(status = 'late'), SUM(status = 'absent'), 'event'
        FROM attendance 
        WHERE qr_code = ? AND (session IS NOT NULL AND session != '')
          AND REPLACE(REPLACE(school_year, 'SY ', ''), 'sy ', '') = ?
        GROUP BY session
    """, (qr_code, normalized_sy))
    daily_events = cursor.fetchall()
    
    conn.close()
    
    subjects = [c for c in subject_contexts if (c[4] or 'subject') == 'subject']
    all_events = [c for c in subject_contexts if c[4] == 'event'] + daily_events
    
    msg = f"<b>STUDENT DOSSIER</b>\n"
    msg += "━━━━━━━━━━━━━━━━━━━━┳═─\n\n"
    msg += f"<b>{name}</b>\n"
    msg += f"<code>{course or 'No Course'}</code>\n"
    msg += f"<b>Overall Scan Traffic:</b>\n"
    
    # Add Progress Bar
    def get_bar(p, l, a):
        total = p + l + a
        if total > 0:
            filled = int((p / total) * 10)
            bar = "█" * filled + "░" * (10 - filled)
            percent = int((p / total) * 100)
            return f"<code>[{bar}]</code> {percent}%"
        return "<code>[░░░░░░░░░░]</code> 0%"

    msg += f"{get_bar(p, l, a)}\n\n"

    msg += "<b>ATTENDANCE SUMMARY</b>\n"
    msg += f"Present: <b>{p}</b> | Late: <b>{l}</b> | Absent: <b>{a}</b>\n\n"
    
    if subjects:
        msg += "<b>SUBJECT RECORDS</b>\n"
        for sub in subjects:
            msg += f"• <b>{sub[0]}</b>\n"
            msg += f"  {get_bar(sub[1], sub[2], sub[3])}\n"
        msg += "\n"

    if all_events:
        msg += "<b>EVENT RECORDS</b>\n"
        for ev in all_events:
            label = str(ev[0]).replace('-', ' ').upper()
            msg += f"• <b>{label}</b>\n"
            msg += f"  {get_bar(ev[1], ev[2], ev[3])}\n"
    
    if not subjects and not all_events:
        msg += "<i>No academic records found for this student.</i>\n"
    
    msg += "\n<i>Data Protocol :: Dossier Retrieval</i>"
    
    return msg

def get_products():
    """Fetches all available products from the database."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT id, name, price, stock, description, is_even_only FROM products WHERE stock > 0")
    products = cursor.fetchall()
    conn.close()
    return products

def get_product(product_id):
    """Fetches a specific product by ID."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT id, name, price, stock, description, is_even_only FROM products WHERE id = ?", (product_id,))
    product = cursor.fetchone()
    conn.close()
    return product

def get_today_stats():
    """Generates a summary of today's attendance."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    today = datetime.now().strftime("%Y-%m-%d")
    
    # General Attendance (Filtered for Specific Events only)
    cursor.execute("SELECT status, COUNT(*) FROM attendance WHERE date = ? AND (session IS NOT NULL AND session != '') GROUP BY status", (today,))
    gen_stats = dict(cursor.fetchall())
    gp, gl, ga = gen_stats.get('present', 0), gen_stats.get('late', 0), gen_stats.get('absent', 0)
    
    # Subject Attendance
    cursor.execute("""
        SELECT s.name, 
            SUM(sa.status = 'present'), 
            SUM(sa.status = 'late'), 
            SUM(sa.status = 'absent')
        FROM subject_attendance sa
        JOIN subjects s ON sa.subject_id = s.id
        WHERE sa.date = ?
        GROUP BY s.id
    """, (today,))
    sub_stats = cursor.fetchall()
    conn.close()
    
    def get_bar(p, l, a):
        total = (p or 0) + (l or 0) + (a or 0)
        if total > 0:
            filled = int((p / total) * 10)
            bar = "█" * filled + "░" * (10 - filled)
            percent = int((p / total) * 100)
            return f"<code>[{bar}]</code> {percent}%"
        return "<code>[░░░░░░░░░░]</code> 0%"

    today_display = datetime.now().strftime("%b %d, %Y")
    
    msg = f"<b>[STATS] TODAY'S SUMMARY</b>\n"
    msg += "━━━━━━━━━━━━━━━━━━━━┳═─\n\n"
    msg += f"Date: {today_display}\n\n"
    
    if gp or gl or ga:
        msg += f"<b>Event Traffic (Daily):</b>\n"
        msg += f"• {get_bar(gp, gl, ga)}\n\n"
    
    if sub_stats:
        msg += "<b>Subject Sessions:</b>\n"
        for name, p, l, a in sub_stats:
            msg += f"• <b>{name}</b>\n"
            msg += f"  {get_bar(p, l, a)}\n"
    
    if not gp and not gl and not ga and not sub_stats:
        msg += "<i>No activity recorded for today.</i>\n"
    else:
        msg += "\n<i>Data Protocol :: Live Update</i>"
        
    return msg

def export_attendance_csv():
    """Exports all attendance data to a CSV file."""
    import csv
    output_path = "attendance_export.csv"
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Join everything for a master export
    cursor.execute("""
        SELECT u.name, u.qr_code, u.course, a.date, a.time, a.status, a.session as context
        FROM attendance a
        JOIN users u ON a.qr_code = u.qr_code
        WHERE (a.session IS NOT NULL AND a.session != '')
        UNION ALL
        SELECT u.name, u.qr_code, u.course, sa.date, sa.time, sa.status, s.name as context
        FROM subject_attendance sa
        JOIN users u ON sa.qr_code = u.qr_code
        JOIN subjects s ON sa.subject_id = s.id
        ORDER BY date DESC, time DESC
    """)
    rows = cursor.fetchall()
    headers = ["Name", "QR Code", "Course", "Date", "Time", "Status", "Context"]
    
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(rows)
    
    conn.close()
    return output_path

def get_student_markdown(qr_code):
    """Generates a clean HTML/Markdown string for PDF conversion."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT name, course FROM users WHERE qr_code = ? LIMIT 1", (qr_code,))
    user = cursor.fetchone()
    if not user:
        conn.close()
        return None
        
    name, course = user
    # Simplified HTML for FPDF HTMLMixin compatibility
    # Modern Header Section
    html = f"""
    <table border="0" width="100%">
        <tr>
            <td width="70%">
                <h1 style="color: #1e293b; margin-bottom: 0;">{name}</h1>
                <p style="color: #64748b; font-size: 10pt;">{course or 'No Course Assigned'}</p>
            </td>
            <td width="30%" align="right">
            </td>
        </tr>
    </table>
    <hr color="#e2e8f0">
    <br>
    """
    
    # Retrieve active school year and normalize
    cursor.execute("SELECT active_school_year FROM settings LIMIT 1")
    setting_row = cursor.fetchone()
    active_sy = setting_row[0].strip() if (setting_row and setting_row[0]) else "SY 2024-2025"
    normalized_sy = active_sy.replace("SY ", "").replace("sy ", "").strip()
    
    # Aggregated Stats
    cursor.execute("""
        SELECT SUM(sa.status='present'), SUM(sa.status='late'), SUM(sa.status='absent') 
        FROM subject_attendance sa
        JOIN subjects s ON sa.subject_id = s.id
        WHERE sa.qr_code=? AND REPLACE(REPLACE(s.school_year, 'SY ', ''), 'sy ', '') = ?
    """, (qr_code, normalized_sy))
    s_stats = cursor.fetchone()
    
    cursor.execute("""
        SELECT SUM(status='present'), SUM(status='late'), SUM(status='absent') 
        FROM attendance 
        WHERE qr_code=? AND (session IS NOT NULL AND session != '')
          AND REPLACE(REPLACE(school_year, 'SY ', ''), 'sy ', '') = ?
    """, (qr_code, normalized_sy))
    d_stats = cursor.fetchone()
    
    p = (s_stats[0] or 0) + (d_stats[0] or 0)
    l = (s_stats[1] or 0) + (d_stats[1] or 0)
    a = (s_stats[2] or 0) + (d_stats[2] or 0)
    
    html += f"""
    <h2 style="color: #1e293b;">Overall Summary</h2>
    <table border="0" width="100%" cellpadding="5">
        <tr bgcolor="#f8fafc">
            <td width="33%"><b>Present:</b> <font color="#059669">{p}</font></td>
            <td width="33%"><b>Late:</b> <font color="#d97706">{l}</font></td>
            <td width="33%"><b>Absent:</b> <font color="#dc2626">{a}</font></td>
        </tr>
    </table>
    <br>
    """
    
    # Breakdown List
    cursor.execute("""
        SELECT s.name, SUM(sa.status='present'), SUM(sa.status='late'), SUM(sa.status='absent')
        FROM subject_attendance sa JOIN subjects s ON sa.subject_id = s.id
        WHERE sa.qr_code = ? AND REPLACE(REPLACE(s.school_year, 'SY ', ''), 'sy ', '') = ?
        GROUP BY s.id
    """, (qr_code, normalized_sy))
    subjects_raw = cursor.fetchall()
    
    cursor.execute("""
        SELECT session, SUM(status='present'), SUM(status='late'), SUM(status='absent')
        FROM attendance 
        WHERE qr_code = ? AND (session IS NOT NULL AND session != '')
          AND REPLACE(REPLACE(school_year, 'SY ', ''), 'sy ', '') = ?
        GROUP BY session
    """, (qr_code, normalized_sy))
    daily_events = cursor.fetchall()
    
    all_contexts = subjects_raw + daily_events
    
    if all_contexts:
        html += '<h2 style="color: #1e293b;">Performance Breakdown</h2>'
        html += '<table border="0" width="100%" cellpadding="8">'
        html += '<thead><tr bgcolor="#1e293b">'
        html += '<th width="64%"><font color="#ffffff">Subject / Event</font></th>'
        html += '<th width="12%" align="center"><font color="#ffffff">P</font></th>'
        html += '<th width="12%" align="center"><font color="#ffffff">L</font></th>'
        html += '<th width="12%" align="center"><font color="#ffffff">A</font></th>'
        html += '</tr></thead>'
        html += '<tbody>'
        
        row_count = 0
        for s in all_contexts:
            row_bg = '#ffffff' if row_count % 2 == 0 else '#f8fafc'
            label = str(s[0]).replace('-', ' ').upper()
            html += f'<tr bgcolor="{row_bg}">'
            html += f'<td><b>{label}</b></td>'
            html += f'<td>{s[1]}</td>'
            html += f'<td>{s[2]}</td>'
            html += f'<td>{s[3]}</td>'
            html += '</tr>'
            row_count += 1
            
        html += '</tbody></table>'
    
    conn.close()
    return html

def generate_pdf_dossier(qr_code):
    """Converts student data to a PDF file and returns the path."""
    html_content = get_student_markdown(qr_code)
    if not html_content:
        return None
        
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("helvetica", size=12)
    
    try:
        # Use HTMLMixin's write_html
        pdf.write_html(html_content)
    except Exception as e:
        print(f"PDF HTML Error: {e}")
        # Fallback to simple text if HTML fails
        pdf.cell(0, 10, f"Error generating rich PDF: {e}", ln=True)
        
    output_path = f"dossier_{qr_code}.pdf"
    pdf.output(output_path)
    return output_path

def queue_worker():
    """Background thread to process pending messages from telegram_queue with anti-spam lock"""
    while True:
        try:
            _, chat_id, _, _, global_bday_img = get_settings()
            if not chat_id:
                time.sleep(10)
                continue
                
            conn = sqlite3.connect(DB_PATH)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            # Fetch pending messages
            cursor.execute("SELECT id, message FROM telegram_queue WHERE status = 'pending' ORDER BY created_at ASC LIMIT 5")
            rows = cursor.fetchall()
            
            for row in rows:
                row_id = row['id']
                message = row['message']
                try:
                    # Update to 'processing' before sending
                    cursor.execute("UPDATE telegram_queue SET status = 'processing' WHERE id = ?", (row_id,))
                    conn.commit()
                    
                    # Handle Animated Messages
                    if "[ANIMATE]" in message:
                        # Format: [ANIMATE]Frame1[STEP]Frame2[STEP]Final
                        clean_msg = message.replace("[ANIMATE]", "").strip()
                        steps = clean_msg.split("[STEP]")
                        
                        # Send first step
                        sent_msg = bot.send_message(chat_id, steps[0], parse_mode='HTML')
                        
                        # Loop through steps (excluding the last one) and edit
                        for i in range(1, len(steps) - 1):
                            time.sleep(1.2) # Small delay for "animation" effect
                            try:
                                bot.edit_message_text(
                                    chat_id=chat_id,
                                    message_id=sent_msg.message_id,
                                    text=steps[i],
                                    parse_mode='HTML'
                                )
                            except Exception as edit_err:
                                print(f"Animation step {i} failed: {edit_err}")
                        
                        # Finalize: Delete loading message and send result as fresh message
                        time.sleep(1.2)
                        try:
                            bot.delete_message(chat_id, sent_msg.message_id)
                        except: pass
                        
                        bot.send_message(chat_id, steps[-1], parse_mode='HTML')
                    else:
                        # Regular Message
                        bot.send_message(chat_id, message, parse_mode='HTML')
                    
                    # Update status on success
                    cursor.execute("UPDATE telegram_queue SET status = 'sent' WHERE id = ?", (row_id,))
                    conn.commit()
                    time.sleep(1) # Small gap between sends
                except Exception as e:
                    print(f"Failed to send queued message (ID: {row_id}): {e}")
                    # Revert to pending on failure to retry later
                    cursor.execute("UPDATE telegram_queue SET status = 'pending' WHERE id = ?", (row_id,))
                    conn.commit()
                    time.sleep(5)
            
            conn.close()
            
        except Exception as e:
            print(f"Queue worker error: {e}")
            
        time.sleep(10) # Check queue every 10 seconds

def birthday_check_worker():
    """Daily worker to send birthday greetings to the group chat"""
    print("Birthday Greeting Worker initialized.")
    while True:
        try:
            _, chat_id, _, _, global_bday_img = get_settings()
            if not chat_id:
                time.sleep(60)
                continue
                
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            
            # Ensure table exists (in case PHP hasn't run yet)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS birthday_greetings (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    qr_code TEXT NOT NULL,
                    year TEXT NOT NULL,
                    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(qr_code, year)
                )
            """)
            conn.commit()
            
            # Use STRFTIME to find matching month/day
            today_md = datetime.now().strftime("%m-%d")
            today_full = datetime.now().strftime("%B %d, %Y")
            current_year = datetime.now().strftime("%Y")
            
            # Find students with birthday today who haven't been greeted yet this year
            cursor.execute("""
                SELECT u.qr_code, u.first_name, u.last_name, u.birthday_image
                FROM users u 
                LEFT JOIN birthday_greetings bg ON u.qr_code = bg.qr_code AND bg.year = ?
                WHERE strftime('%m-%d', u.birthday) = ? 
                  AND u.deleted_at IS NULL
                  AND bg.id IS NULL
            """, (current_year, today_md))
            
            birthdays = cursor.fetchall()
            
            if birthdays:
                try:
                    # Animated Progress Sweep - Only once per batch
                    sweep_msg = bot.send_message(chat_id, "[SEARCH] <b>SYSTEM SWEEP:</b> Scanning database...\n<code>[░░░░░░░░░░] 0%</code>", parse_mode='HTML')
                    
                    for i in range(1, 6):
                        time.sleep(0.4)
                        filled = i * 2
                        bar = "█" * filled + "░" * (10 - filled)
                        bot.edit_message_text(
                            f"[SEARCH] <b>SYSTEM SWEEP:</b> Scanning database...\n<code>[{bar}] {i*20}%</code>",
                            chat_id,
                            sweep_msg.message_id,
                            parse_mode='HTML'
                        )
                    
                    time.sleep(0.3)
                    bot.delete_message(chat_id, sweep_msg.message_id)
                except Exception as e:
                    print(f"Sweep animation error: {e}")

                for qr_code, f_name, l_name, student_bday_img in birthdays:
                    try:
                        # Determine which image to use (Priority: Student > Global)
                        img_to_use = student_bday_img if student_bday_img else global_bday_img
                        
                        # Clean image path (absolute path for local files if they don't start with http)
                        if img_to_use and not img_to_use.startswith('http'):
                            # Resolve path relative to the root of the project
                            base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                            img_to_use = os.path.join(base_dir, img_to_use)

                        # Ultra-Minimalist 'Pure Data' UI (No Labels, Full Date)
                        msg = (
                            "<b>[BDAY] BIRTHDAY NOTICE</b>\n"
                            "━━━━━━━━━━━━━━━━━━━━┳═─\n\n"
                            f"Date: {today_full}\n\n"
                            f"<b>{f_name} {l_name}</b>\n"
                            "<i>Wishing you a great day!</i>\n\n"
                            "<i>Data Protocol :: Celebration</i>"
                        )
                        
                        if img_to_use:
                            try:
                                if img_to_use.startswith('http'):
                                    bot.send_photo(chat_id, img_to_use, caption=msg, parse_mode='HTML')
                                else:
                                    with open(img_to_use, 'rb') as photo:
                                        bot.send_photo(chat_id, photo, caption=msg, parse_mode='HTML')
                            except Exception as photo_err:
                                print(f"Photo send failed, falling back to text: {photo_err}")
                                bot.send_message(chat_id, msg, parse_mode='HTML')
                        else:
                            bot.send_message(chat_id, msg, parse_mode='HTML')
                        
                        # Mark as sent
                        cursor.execute("INSERT INTO birthday_greetings (qr_code, year) VALUES (?, ?)", (qr_code, current_year))
                        conn.commit()
                        print(f"Sent birthday greeting to {f_name} {l_name}")
                        time.sleep(1) # Small gap between messages
                    except Exception as e:
                        print(f"Failed to send birthday message: {e}")
            
            conn.close()
            
        except Exception as e:
            print(f"Birthday worker error: {e}")
            
        # Check every 4 hours to avoid heavy DB load but catch up if bot was down
        time.sleep(14400) 

# Main Loop
print("Starting up Attendance Web-Bot connector...")
while True:
    TOKEN, _, _, _, _ = get_settings()
    if not TOKEN:
        print("Waiting for Telegram Bot Token to be set in Settings...")
        time.sleep(10)
        continue
    
    print("Initialize Bot (with 90s timeout for stability)...")
    bot = telebot.TeleBot(TOKEN, parse_mode='HTML', threaded=True)
    # Global timeouts for all requests
    telebot.apihelper.CONNECT_TIMEOUT = 30
    telebot.apihelper.READ_TIMEOUT = 90

    def get_admin_main_keyboard():
        markup = ReplyKeyboardMarkup(resize_keyboard=True)
        markup.row(KeyboardButton("Search Student"), KeyboardButton("Record Attendance"))
        markup.row(KeyboardButton("Today's Stats"), KeyboardButton("Announce"))
        markup.row(KeyboardButton("Export CSV"), KeyboardButton("All Dossiers"), KeyboardButton("Get Database"))
        return markup

    def get_active_subjects():
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("SELECT id, name FROM subjects WHERE is_active = 1 ORDER BY name ASC")
        rows = cursor.fetchall()
        conn.close()
        return rows

    def get_eligible_students(recording_type, subject_id=None):
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        if recording_type == 'daily':
            cursor.execute("""
                SELECT qr_code, name, course, student_type 
                FROM users 
                WHERE deleted_at IS NULL 
                ORDER BY name ASC
            """)
        else:
            cursor.execute("""
                SELECT qr_code, name, course, student_type 
                FROM users 
                WHERE deleted_at IS NULL 
                  AND (
                    student_type != 'irregular' 
                    OR qr_code IN (SELECT qr_code FROM student_subjects WHERE subject_id = ?)
                  )
                ORDER BY name ASC
            """, (subject_id,))
        students = cursor.fetchall()
        conn.close()
        return students

    def show_subject_select_screen(chat_id, message_id, state_data):
        state_data['state'] = 'recording_subject_select'
        subjects = get_active_subjects()
        
        markup = InlineKeyboardMarkup(row_width=1)
        for sub_id, name in subjects:
            markup.add(InlineKeyboardButton(name, callback_data=f"rec_subsel_{sub_id}"))
            
        markup.row(InlineKeyboardButton("Back", callback_data="rec_back_mode"),
                   InlineKeyboardButton("Cancel", callback_data="rec_cancel"))
                   
        msg_text = (
            "<b>RECORD ATTENDANCE: SELECT SUBJECT</b>\n"
            "━━━━━━━━━━━━━━━━━━━━┳═─\n\n"
            "Select the active subject class:"
        )
        if not subjects:
            msg_text += "\n\n<i>No active subjects found.</i>"
            
        bot.edit_message_text(msg_text, chat_id, message_id, reply_markup=markup, parse_mode='HTML')

    def show_date_select_screen(chat_id, message_id, state_data):
        state_data['state'] = 'recording_date_select'
        today_str = datetime.now().strftime("%Y-%m-%d")
        
        markup = InlineKeyboardMarkup()
        markup.row(InlineKeyboardButton(f"Today ({today_str})", callback_data="rec_date_today"),
                   InlineKeyboardButton("Custom Date", callback_data="rec_date_custom"))
        
        back_callback = "rec_back_mode" if state_data['recording_type'] == 'daily' else "rec_back_subjects"
        
        markup.row(InlineKeyboardButton("Back", callback_data=back_callback),
                   InlineKeyboardButton("Cancel", callback_data="rec_cancel"))
        
        context_name = "Daily Attendance" if state_data['recording_type'] == 'daily' else state_data['subject_name']
        msg_text = (
            f"<b>RECORD ATTENDANCE: DATE</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
            f"Context: <b>{context_name}</b>\n\n"
            f"Select the target date for recording:"
        )
        
        bot.edit_message_text(msg_text, chat_id, message_id, reply_markup=markup, parse_mode='HTML')

    def show_custom_date_buttons_screen(chat_id, message_id, state_data):
        import datetime as dt_mod
        state_data['state'] = 'recording_date_custom_select'
        
        days = []
        for i in range(1, 8):
            d = datetime.now() - dt_mod.timedelta(days=i)
            days.append(d)
            
        markup = InlineKeyboardMarkup()
        row = []
        for d in days:
            date_str = d.strftime("%Y-%m-%d")
            day_label = d.strftime("%Y-%m-%d (%a)")
            row.append(InlineKeyboardButton(day_label, callback_data=f"rec_dateval_{date_str}"))
            if len(row) == 2:
                markup.row(*row)
                row = []
        if row:
            markup.row(*row)
            
        markup.row(InlineKeyboardButton("Back", callback_data="rec_back_dates"),
                   InlineKeyboardButton("Cancel", callback_data="rec_cancel"))
                   
        context_name = "Daily Attendance" if state_data['recording_type'] == 'daily' else state_data['subject_name']
        msg_text = (
            f"<b>RECORD ATTENDANCE: SELECT DATE</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
            f"Context: <b>{context_name}</b>\n\n"
            f"Select one of the past 7 days to record attendance:"
        )
        
        bot.edit_message_text(msg_text, chat_id, message_id, reply_markup=markup, parse_mode='HTML')

    def show_student_select_screen(chat_id, message_id, state_data):
        state_data['state'] = 'recording_student_select'
        
        recording_type = state_data['recording_type']
        subject_id = state_data.get('subject_id')
        students = get_eligible_students(recording_type, subject_id)
        
        total_students = len(students)
        current_page = state_data.get('current_page', 0)
        page_size = 5
        max_pages = (total_students + page_size - 1) // page_size if total_students > 0 else 1
        
        # bounds check
        if current_page < 0:
            current_page = 0
        elif current_page >= max_pages:
            current_page = max_pages - 1
        state_data['current_page'] = current_page
        
        start_idx = current_page * page_size
        end_idx = min(start_idx + page_size, total_students)
        page_students = students[start_idx:end_idx]
        
        markup = InlineKeyboardMarkup(row_width=1)
        
        for qr_code, name, course, student_type in page_students:
            course_tag = f" ({course})" if course else ""
            type_tag = " (Irregular)" if student_type == 'irregular' else ""
            btn_text = f"{name}{course_tag}{type_tag}"
            markup.add(InlineKeyboardButton(btn_text, callback_data=f"rec_stusel_{qr_code}"))
            
        nav_row = []
        if current_page > 0:
            nav_row.append(InlineKeyboardButton("<< Prev", callback_data="rec_page_prev"))
        else:
            nav_row.append(InlineKeyboardButton("<< Prev", callback_data="rec_noop"))
            
        nav_row.append(InlineKeyboardButton(f"Page {current_page + 1}/{max_pages}", callback_data="rec_noop"))
        
        if current_page + 1 < max_pages:
            nav_row.append(InlineKeyboardButton("Next >>", callback_data="rec_page_next"))
        else:
            nav_row.append(InlineKeyboardButton("Next >>", callback_data="rec_noop"))
            
        markup.row(*nav_row)
        
        markup.row(InlineKeyboardButton("Back", callback_data="rec_back_dates"),
                   InlineKeyboardButton("Cancel", callback_data="rec_cancel"))
        
        context_name = "Daily Attendance" if recording_type == 'daily' else state_data.get('subject_name', 'Subject')
        msg_text = (
            f"<b>RECORD ATTENDANCE: SELECT STUDENT</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
            f"Context: <b>{context_name}</b>\n"
            f"Date: <b>{state_data['date']}</b>\n\n"
            f"Select a student from the list below to record attendance:"
        )
        if not students:
            msg_text += "\n\n<i>No eligible students found.</i>"
            
        bot.edit_message_text(msg_text, chat_id, message_id, reply_markup=markup, parse_mode='HTML')

    def show_status_select_screen(chat_id, message_id, state_data):
        state_data['state'] = 'recording_status_select'
        
        markup = InlineKeyboardMarkup()
        markup.row(InlineKeyboardButton("Present", callback_data="rec_status_present"),
                   InlineKeyboardButton("Late", callback_data="rec_status_late"),
                   InlineKeyboardButton("Absent", callback_data="rec_status_absent"))
        markup.row(InlineKeyboardButton("Back", callback_data="rec_back_student_select"),
                   InlineKeyboardButton("Cancel", callback_data="rec_cancel"))
        
        context_name = "Daily Attendance" if state_data['recording_type'] == 'daily' else state_data['subject_name']
        msg_text = (
            f"<b>RECORD ATTENDANCE: STATUS</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
            f"Context: <b>{context_name}</b>\n"
            f"Date: <b>{state_data['date']}</b>\n"
            f"Student: <b>{state_data['student_name']}</b>\n\n"
            f"Choose attendance status for the student:"
        )
        
        bot.edit_message_text(msg_text, chat_id, message_id, reply_markup=markup, parse_mode='HTML')

    def handle_record_attendance(message):
        """Starts the attendance recording process."""
        _, _, ADMIN_ID, _, _ = get_settings()
        if str(message.from_user.id) != str(ADMIN_ID).strip() or message.chat.type != 'private':
            return
            
        markup = InlineKeyboardMarkup()
        markup.row(InlineKeyboardButton("Daily Attendance", callback_data="rec_mode_daily"),
                   InlineKeyboardButton("Subject Attendance", callback_data="rec_mode_subject"))
        markup.row(InlineKeyboardButton("Cancel", callback_data="rec_cancel"))
        
        msg_text = (
            "<b>RECORD ATTENDANCE</b>\n"
            "━━━━━━━━━━━━━━━━━━━━┳═─\n\n"
            "Select the type of attendance you wish to record:"
        )
        
        frame_msg = bot.send_message(message.chat.id, msg_text, reply_markup=markup, parse_mode='HTML')
        
        with user_states_lock:
            user_states[message.from_user.id] = {
                'state': 'recording_mode_select',
                'frame_msg_id': frame_msg.message_id
            }

    def trigger_announcement_confirmation(user_id, chat_id, content_type):
        with user_states_lock:
            state_data = user_states.get(user_id)
            if not state_data or state_data.get('state') != 'announcing':
                return
            
            msg_ids = state_data.get('msg_ids', [])
            draft_id = state_data.get('draft_msg_id')
            if not msg_ids or not draft_id:
                return
            
            state_data['timer'] = None
            count = len(msg_ids)
            
            markup = InlineKeyboardMarkup()
            markup.row(InlineKeyboardButton("[OK] Confirm Broadcast", callback_data="ann_confirm"), 
                      InlineKeyboardButton("[X] Cancel", callback_data="ann_cancel"))
            
            msg = f"[BOX] <b>ANNOUNCEMENT READY</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nStatus: <b>Buffer Stable</b>\nItems: <b>{count} total</b>\n\nReady to deliver these items to the group chat?"
            try:
                bot.edit_message_text(msg, chat_id, draft_id, parse_mode='HTML', reply_markup=markup)
            except: pass


    @bot.message_handler(commands=['start', 'help'])
    def send_welcome(message):
        _, _, ADMIN_ID, _, _ = get_settings()
        is_admin = str(message.from_user.id) == str(ADMIN_ID).strip()
        
        welcome_text = (
            "<b>ATTENDANCE INTERFACE</b>\n\n"
            "Welcome. Available commands:\n"
            "• <code>/search [Name/ID]</code>\n"
            "• <code>/order</code> (Store/Products)\n"
            "• <code>/pdf [ID]</code> (Export PDF)\n"
            "• <code>/birthdays</code> (Upcoming)\n"
            "• <code>/bdaysearch [Query]</code> (Search B-Day)\n"
        )
        
        if is_admin:
            welcome_text += (
                "• <code>/today</code> (Daily Stats)\n"
                "• <code>/export</code> (Export CSV)\n"
                "• <code>/getdb</code> (Admin DB Access)\n\n"
                "<i>Use the menu below for quick actions.</i>"
            )
        else:
            welcome_text += "\n<i>Please contact an administrator for full access.</i>"
            
        bot.reply_to(message, welcome_text, reply_markup=get_admin_main_keyboard() if is_admin else None)

    @bot.message_handler(commands=['announce', 'cancel'])
    def handle_announce_command(message):
        _, _, ADMIN_ID, _, _ = get_settings()
        if str(message.from_user.id) != str(ADMIN_ID).strip():
            return
            
        if message.chat.type != 'private':
            return # Admin controls only valid in Private Chat
            
        if message.text.startswith('/cancel'):
            with user_states_lock:
                state = user_states.get(message.from_user.id)
                if state and state.get('timer'):
                    state['timer'].cancel()
                user_states[message.from_user.id] = {'state': 'idle'}
            bot.reply_to(message, "[X] <b>Announcement cancelled.</b> Returning to normal mode.", reply_markup=get_admin_main_keyboard())
            return
            
        with user_states_lock:
            # Start drafting session
            markup = InlineKeyboardMarkup()
            markup.row(InlineKeyboardButton("[OK] Broadcast Now", callback_data="ann_confirm"), 
                      InlineKeyboardButton("[X] Discard", callback_data="ann_cancel"))
            
            draft_msg = bot.send_message(message.chat.id, "[ANNOUNCE] <b>ANNOUNCEMENT DRAFT</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nStatus: <b>Ready for Input</b>\nItems: <code>[0]</code>\n\n<i>Send text, photos, or files to add them to your draft.</i>", parse_mode='HTML', reply_markup=markup)
            
            user_states[message.from_user.id] = {
                'state': 'announcing', 
                'msg_ids': [], 
                'timer': None,
                'draft_msg_id': draft_msg.message_id
            }

    @bot.message_handler(commands=['today'])
    def handle_today(message):
        _, _, ADMIN_ID, _, _ = get_settings()
        if str(message.from_user.id) != str(ADMIN_ID).strip() or message.chat.type != 'private':
            return
        try:
            bot.send_chat_action(message.chat.id, 'typing')
            stats = get_today_stats()
            bot.reply_to(message, stats)
        except Exception as e:
            bot.reply_to(message, f"[X] <b>Command Error:</b>\n<code>{str(e)}</code>")

    @bot.message_handler(commands=['export'])
    def handle_export(message):
        _, _, ADMIN_ID, _, _ = get_settings()
        if str(message.from_user.id) != str(ADMIN_ID).strip() or message.chat.type != 'private':
            return
        bot.send_chat_action(message.chat.id, 'upload_document')
        try:
            path = export_attendance_csv()
            with open(path, 'rb') as f:
                bot.send_document(message.chat.id, f, caption="[STATS] Full Attendance Export (CSV)")
            os.remove(path)
        except Exception as e:
            bot.reply_to(message, f"[X] Export failed: {e}")

    def animate_loading(chat_id, title="GENERATING DOSSIER", speed=0.3, message_id=None):
        """Standardized loading animation. Can send a new message or edit an existing one."""
        try:
            if message_id:
                bot.edit_message_text(f"[SYNC] <b>{title}</b>\n<code>[░░░░░░░░░░] 0%</code>", chat_id, message_id, parse_mode='HTML')
                working_id = message_id
            else:
                msg = bot.send_message(chat_id, f"[SYNC] <b>{title}</b>\n<code>[░░░░░░░░░░] 0%</code>", parse_mode='HTML')
                working_id = msg.message_id
                
            for i in range(1, 6):
                time.sleep(speed)
                filled = i * 2
                bar = "█" * filled + "░" * (10 - filled)
                bot.edit_message_text(
                    f"[SYNC] <b>{title}</b>\n<code>[{bar}] {i*20}%</code>",
                    chat_id, working_id, parse_mode='HTML'
                )
            return working_id
        except: return message_id

    @bot.message_handler(commands=['pdf'])
    def handle_pdf_export(message):
        args = message.text.split(maxsplit=1)
        if len(args) < 2:
            bot.reply_to(message, "<b>[DOC] PDF Export</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nPlease provide a student ID.\n\nExample: <code>/pdf 12345</code>")
            return
            
        qr_code = args[1].strip()
        loading_id = animate_loading(message.chat.id)
        bot.send_chat_action(message.chat.id, 'upload_document')
        
        try:
            pdf_path = generate_pdf_dossier(qr_code)
            if pdf_path and os.path.exists(pdf_path):
                with open(pdf_path, 'rb') as f:
                    bot.send_document(message.chat.id, f, caption=f"[DOC] Attendance Dossier")
                os.remove(pdf_path) # Cleanup
                if loading_id: bot.delete_message(message.chat.id, loading_id)
            else:
                if loading_id: bot.delete_message(message.chat.id, loading_id)
                bot.reply_to(message, "[X] Failed to generate PDF. Ensure ID is correct.")
        except Exception as e:
            if loading_id: bot.delete_message(message.chat.id, loading_id)
            bot.reply_to(message, f"[X] Error: {e}")
            
    # --- NEW: Upcoming Birthdays Command ---
    @bot.message_handler(commands=['birthdays'])
    def show_upcoming_birthdays(message):
        try:
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute("SELECT first_name, last_name, birthday FROM users WHERE birthday IS NOT NULL AND deleted_at IS NULL")
            rows = cursor.fetchall()
            conn.close()
            
            if not rows:
                bot.reply_to(message, "<i>No student records found.</i>", parse_mode='HTML')
                return
                
            today = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
            upcoming = []
            
            for f_name, l_name, b_day_str in rows:
                try:
                    # Parse birthday (assumes YYYY-MM-DD)
                    bday_dt = datetime.strptime(b_day_str, '%Y-%m-%d')
                    # Find next occurrence
                    this_year_bday = bday_dt.replace(year=today.year)
                    if this_year_bday < today:
                        next_bday = this_year_bday.replace(year=today.year + 1)
                    else:
                        next_bday = this_year_bday
                        
                    days_left = (next_bday - today).days
                    upcoming.append({
                        'name': f"{f_name} {l_name}",
                        'date': next_bday.strftime("%B %d"),
                        'days': days_left
                    })
                except: continue # Skip invalid dates
                
            # Sort by nearest
            upcoming.sort(key=lambda x: x['days'])
            top_5 = upcoming[:5]
            
            if not top_5:
                bot.reply_to(message, "<i>No upcoming birthdays detected.</i>", parse_mode='HTML')
                return
                
            msg_body = "<b>[DATE] UPCOMING BIRTHDAYS</b>\n"
            msg_body += "━━━━━━━━━━━━━━━━━━━━┳═─\n\n"
            msg_body += f"Date: {datetime.now().strftime('%b %d, %Y')}\n\n"
            
            for i, stu in enumerate(top_5, 1):
                msg_body += f"<b>{i}. {stu['name']}</b>\n"
                msg_body += f"<code>{stu['date']} · {stu['days']} Days Left</code>\n\n"
                
            msg_body += "<i>Data Protocol :: System Retrieval</i>"
            
            bot.send_message(message.chat.id, msg_body, parse_mode='HTML')
            
        except Exception as e:
            print(f"Birthdays Error: {e}")
            bot.reply_to(message, "<i>System error retrieving records.</i>", parse_mode='HTML')

    @bot.message_handler(commands=['birthday_search', 'bdaysearch'])
    def handle_birthday_search(message):
        args = message.text.split(maxsplit=1)
        if len(args) < 2:
            bot.reply_to(message, "<b>[SEARCH] BIRTHDAY SEARCH</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nPlease provide a name or student ID.\n\nExample: <code>/bdaysearch delin</code>")
            return
            
        query = args[1].strip()
        bot.send_chat_action(message.chat.id, 'typing')
        
        try:
            # 1. Animated Progress Sweep
            sweep_msg = bot.send_message(message.chat.id, "[SEARCH] <b>SYSTEM SWEEP:</b> Scanning database...\n<code>[░░░░░░░░░░] 0%</code>", parse_mode='HTML')
            
            for i in range(1, 6):
                time.sleep(0.3)
                filled = i * 2
                bar = "█" * filled + "░" * (10 - filled)
                bot.edit_message_text(
                    f"[SEARCH] <b>SYSTEM SWEEP:</b> Scanning database...\n<code>[{bar}] {i*20}%</code>",
                    message.chat.id,
                    sweep_msg.message_id,
                    parse_mode='HTML'
                )
            
            time.sleep(0.2)
            bot.delete_message(message.chat.id, sweep_msg.message_id)

            # 2. Database Search
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            search_query = f"%{query}%"
            cursor.execute("""
                SELECT first_name, last_name, birthday 
                FROM users 
                WHERE (qr_code = ? OR name LIKE ? OR first_name LIKE ? OR last_name LIKE ?)
                AND birthday IS NOT NULL 
                AND deleted_at IS NULL
                LIMIT 5
            """, (query, search_query, search_query, search_query))
            rows = cursor.fetchall()
            conn.close()

            if not rows:
                bot.send_message(message.chat.id, f"<i>No birthday records found for: '{query}'</i>", parse_mode='HTML')
                return

            msg_body = "<b>[SEARCH] BIRTHDAY SEARCH RESULTS</b>\n"
            msg_body += "━━━━━━━━━━━━━━━━━━━━┳═─\n\n"
            msg_body += f"Query: '{query}'\n\n"
            
            for f_name, l_name, b_day_str in rows:
                try:
                    bday_dt = datetime.strptime(b_day_str, '%Y-%m-%d')
                    full_date = bday_dt.strftime("%B %d, %Y")
                    msg_body += f"<b>{f_name} {l_name}</b>\n"
                    msg_body += f"<code>{full_date}</code>\n\n"
                except:
                    msg_body += f"<b>{f_name} {l_name}</b>\n"
                    msg_body += f"<code>{b_day_str}</code>\n\n"

            msg_body += "<b>───────────────────</b>\n"
            msg_body += "<i>Data Protocol 2.0 :: Admin Retrieval</i>"
            
            bot.send_message(message.chat.id, msg_body, parse_mode='HTML')

        except Exception as e:
            print(f"B-Day Search Error: {e}")
            bot.reply_to(message, "<i>System error during search.</i>", parse_mode='HTML')

    @bot.message_handler(commands=['order'])
    def handle_order_command(message):
        """Starts the ordering process with a frame-animated UI."""
        products = get_products()
        if not products:
            bot.reply_to(message, "[BOX] <b>ORDER SYSTEM</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\n<i>Currently, no products are available for order.</i>")
            return
            
        _, _, _, store_name, _ = get_settings()
        markup = InlineKeyboardMarkup(row_width=1)
        for p_id, p_name, p_price, p_stock, _, _ in products:
            markup.add(InlineKeyboardButton(f"{p_name} - ₱{p_price}", callback_data=f"ord_sel_{p_id}"))
        markup.add(InlineKeyboardButton("[X] Cancel", callback_data="ord_cancel"))
        
        frame_msg = bot.send_message(
            message.chat.id, 
            f"[BOX] <b>{store_name}</b>\n━━━━━━━━━━━━━━━━━━━━\nSelect a product you wish to order from the list below.\n\n<i>All orders are subject to stock availability and validation.</i>",
            reply_markup=markup
        )
        # Initialize state
        user_states[message.from_user.id] = {
            'state': 'ordering_select',
            'frame_msg_id': frame_msg.message_id
        }

    @bot.callback_query_handler(func=lambda call: call.data.startswith('ord_'))
    def handle_order_callbacks(call):
        state_data = user_states.get(call.from_user.id)
        if not state_data or state_data.get('frame_msg_id') != call.message.message_id:
            # If state is missing or message is different, but it's a selection, we can try to recover
            if call.data.startswith('ord_sel_'):
                user_states[call.from_user.id] = {'state': 'ordering_select', 'frame_msg_id': call.message.message_id}
                state_data = user_states[call.from_user.id]

        if call.data == 'ord_cancel':
            bot.edit_message_text(
                "[X] <b>Order Cancelled.</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nThe ordering process was terminated. Feel free to browse again anytime.",
                chat_id=call.message.chat.id,
                message_id=call.message.message_id
            )
            user_states[call.from_user.id] = {'state': 'idle'}
            bot.answer_callback_query(call.id)
            return

        if call.data.startswith('ord_sel_'):
            p_id = int(call.data.split('_')[2])
            product = get_product(p_id)
            
            if not product or product[2] <= 0: # Check stock
                bot.answer_callback_query(call.id, "Sorry, this product is out of stock.")
                return
                
            state_data['selected_product'] = product
            state_data['state'] = 'ordering_qty'
            
            p_name, p_price, p_stock = product[1], product[2], product[3]
            is_even_only = product[5]
            
            msg = (
                f"[CART] <b>ORDERING: {p_name}</b>\n"
                f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
                f"Price: <b>₱{p_price}</b>\n"
                f"Stock: <b>{p_stock} pcs</b>\n\n"
                f"<b>STEP: Enter Quantity</b>\n"
                f"Please type the quantity you wish to order.\n"
            )
            if is_even_only:
                msg += f"[WARN] <i>Note: Must be an <b>even number</b>.</i>"
            
            markup = InlineKeyboardMarkup()
            markup.add(InlineKeyboardButton("[X] Abort", callback_data="ord_cancel"))
            
            bot.edit_message_text(msg, chat_id=call.message.chat.id, message_id=call.message.message_id, reply_markup=markup)
            bot.answer_callback_query(call.id)

        if call.data == 'ord_confirm':
            p_id, p_name, p_price = state_data['selected_product'][0:3]
            qty = state_data['quantity']
            total = state_data['total_price']
            name = state_data['customer_name']
            
            # Final Stock Check wrap in transaction
            try:
                conn = sqlite3.connect(DB_PATH)
                cursor = conn.cursor()
                cursor.execute("SELECT stock FROM products WHERE id = ?", (p_id,))
                current_stock = cursor.fetchone()[0]
                
                if current_stock < qty:
                    bot.edit_message_text("[X] <b>Stock Error</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nSomeone else might have ordered. Low stock alert.", chat_id=call.message.chat.id, message_id=call.message.message_id)
                    conn.close()
                    return
                    
                # Record Order
                cursor.execute("""
                    INSERT INTO orders (product_id, telegram_id, customer_name, quantity, total_price)
                    VALUES (?, ?, ?, ?, ?)
                """, (p_id, str(call.from_user.id), name, qty, total))
                
                # Deduct Stock
                cursor.execute("UPDATE products SET stock = stock - ? WHERE id = ?", (qty, p_id))
                
                conn.commit()
                conn.close()
                
                bot.edit_message_text(
                    f"[OK] <b>ORDER PLACED!</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\n"
                    f"<b>Product:</b> {p_name}\n"
                    f"<b>Quantity:</b> {qty} pcs\n"
                    f"<b>Total:</b> ₱{total}\n\n"
                    f"Thank you, <b>{name}</b>. Your order is recorded and will be processed shortly.",
                    chat_id=call.message.chat.id,
                    message_id=call.message.message_id
                )
                
                # Notify Admin
                _, _, ADMIN_ID, _, _ = get_settings()
                if ADMIN_ID:
                    admin_msg = (
                        f"[CART] <b>NEW ORDER RECEIVED</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
                        f"<b>Item:</b> {p_name}\n"
                        f"<b>Qty:</b> {qty}\n"
                        f"<b>Total:</b> ₱{total}\n"
                        f"<b>Customer:</b> {name} (@{call.from_user.username or 'NoUser'})\n"
                    )
                    bot.send_message(ADMIN_ID, admin_msg)
                
            except Exception as e:
                print(f"Order error: {e}")
                bot.edit_message_text("[X] <b>Order Failed</b>\nSystem error. Try again later.", chat_id=call.message.chat.id, message_id=call.message.message_id)
            
            user_states[call.from_user.id] = {'state': 'idle'}
            bot.answer_callback_query(call.id)

    @bot.message_handler(commands=['orders'])
    def handle_view_orders(message):
        """Allows admins to view the latest orders from the database."""
        _, _, ADMIN_ID, _, _ = get_settings()
        if str(message.from_user.id) != str(ADMIN_ID).strip() or message.chat.type != 'private':
            return
            
        try:
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute("""
                SELECT o.customer_name, p.name, o.quantity, o.total_price, o.status, o.created_at
                FROM orders o JOIN products p ON o.product_id = p.id
                ORDER BY o.created_at DESC LIMIT 15
            """)
            orders = cursor.fetchall()
            conn.close()
            
            if not orders:
                bot.reply_to(message, "[LIST] <b>ORDER LOG</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\n<i>No orders recorded in the system.</i>")
                return
                
            msg = "[LIST] <b>LATEST ORDERS (15)</b>\n"
            msg += "━━━━━━━━━━━━━━━━━━━━┳═─\n\n"
            
            for cust, item, qty, total, status, date in orders:
                # Status prefix
                status_icon = "[WAIT]" if status == 'pending' else "[OK]"
                date_str = datetime.strptime(date, '%Y-%m-%d %H:%M:%S').strftime('%b %d, %H:%M')
                
                msg += f"<b>{cust}</b> · <i>{date_str}</i>\n"
                msg += f" {status_icon} <code>{item} x{qty}</code> | <b>₱{total}</b>\n\n"
                
            msg += "━━━━━━━━━━━━━━━━━━━━┳═─\n"
            msg += "<i>Tip: View full logs on the Web Dash.</i>"
            
            bot.send_message(message.chat.id, msg, parse_mode='HTML')
            
        except Exception as e:
            print(f"Orders view error: {e}")
            bot.reply_to(message, "[X] System error retrieving orders.")

    @bot.message_handler(commands=['search'])
    def handle_search(message):
        args = message.text.split(maxsplit=1)
        if len(args) < 2:
            bot.reply_to(message, "<b>[SEARCH] Search Required</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nPlease provide a name or ID.\n\nExample: <code>/search John</code>")
            return
        
        query = args[1].strip()
        bot.send_chat_action(message.chat.id, 'typing')
        results = find_students(query)
        
        if not results:
            bot.reply_to(message, f"<b>No Match Found</b>\nNo records found for '<b>{query}</b>'.")
        elif len(results) == 1:
            # Single match - Add Animation
            loading_id = animate_loading(message.chat.id, title="RETRIEVING PROFILE", speed=0.2)
            stats = get_student_stats(results[0][0])
            if loading_id: bot.delete_message(message.chat.id, loading_id)
            bot.reply_to(message, stats)
        else:
            # Multiple matches
            markup = InlineKeyboardMarkup(row_width=1)
            for qr_code, name, course in results[:5]:
                course_tag = f" ({course})" if course else ""
                markup.add(InlineKeyboardButton(f"{name}{course_tag}", callback_data=f"view_{qr_code}"))
            
            if len(results) > 5:
                bot.reply_to(message, f"<b>Multiple Results</b>\nFound several matches for '<b>{query}</b>'.\n\n<i>Select a profile:</i>", reply_markup=markup)
            else:
                bot.reply_to(message, f"<b>Multiple Results</b>\nFound {len(results)} matches.\n\n<i>Select a profile:</i>", reply_markup=markup)

    @bot.message_handler(commands=['dossier_all'])
    def handle_dossier_all(message):
        _, _, ADMIN_ID, _, _ = get_settings()
        if str(message.from_user.id) != str(ADMIN_ID).strip() or message.chat.type != 'private':
            return
            
        bot.send_message(message.chat.id, "[SYNC] <b>BATCH PROCESSING</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nInitializing mass dossier generation...")
        students = get_all_active_students()
        total = len(students)
        
        if total == 0:
            bot.send_message(message.chat.id, "[X] No active students found.")
            return

        status_msg = bot.send_message(message.chat.id, f"[STATS] <b>Dossier Batch (0/{total})</b>\n<code>[░░░░░░░░░░] 0%</code>", parse_mode='HTML')
        
        for i, (qr_code, name) in enumerate(students, 1):
            try:
                # Individual Animation for 'Data Retrieval' feel
                load_msg = bot.send_message(message.chat.id, f"[SYNC] <b>FETCHING:</b> {name}\n<code>[░░░░░░░░░░] 0%</code>", parse_mode='HTML')
                for step in range(1, 4):
                    time.sleep(0.2)
                    filled = step * 3
                    bar = "█" * filled + "░" * (10 - filled)
                    try: bot.edit_message_text(f"[SYNC] <b>FETCHING:</b> {name}\n<code>[{bar}] {step*33}%</code>", message.chat.id, load_msg.message_id, parse_mode='HTML')
                    except: pass
                
                stats = get_student_stats(qr_code)
                
                # Cleanup loading message before sending final stats
                try: bot.delete_message(message.chat.id, load_msg.message_id)
                except: pass
                
                bot.send_message(message.chat.id, stats, parse_mode='HTML')
                
                # Update Overall Progress Message
                if i % 3 == 0 or i == total:
                    filled = int((i / total) * 10)
                    bar = "█" * filled + "░" * (10 - filled)
                    percent = int((i / total) * 100)
                    bot.edit_message_text(
                        f"[STATS] <b>Dossier Batch ({i}/{total})</b>\n<code>[{bar}] {percent}%</code>",
                        message.chat.id, status_msg.message_id, parse_mode='HTML'
                    )
                
                time.sleep(0.4) # Stabilizing delay
            except Exception as e:
                print(f"Error sending dossier for {name}: {e}")
                
        bot.send_message(message.chat.id, f"[OK] <b>BATCH COMPLETED</b>\nSent {total} dossiers successfully.")

    @bot.callback_query_handler(func=lambda call: call.data.startswith('view_'))
    def handle_selection(call):
        qr_code = call.data.split('_', 1)[1]
        # Show mid-edit animation
        animate_loading(call.message.chat.id, title="FETCHING DATA", speed=0.2, message_id=call.message.message_id)
        
        stats = get_student_stats(qr_code)
        if stats:
            # Edit the message with stats
            markup = InlineKeyboardMarkup()
            markup.row(InlineKeyboardButton("[DOC] Export PDF Dossier", callback_data=f"pdf_exp_{qr_code}"))
            markup.row(InlineKeyboardButton("[SYNC] New Search", switch_inline_query_current_chat=""))
            bot.edit_message_text(stats, chat_id=call.message.chat.id, message_id=call.message.message_id, parse_mode='HTML', reply_markup=markup)
        else:
            bot.answer_callback_query(call.id, "Student not found.")

    @bot.callback_query_handler(func=lambda call: call.data.startswith('pdf_exp_'))
    def handle_pdf_callback(call):
        qr_code = call.data.split('_', 2)[2]
        bot.answer_callback_query(call.id, "Preparing Dossier...")
        
        loading_id = animate_loading(call.message.chat.id, title="GENERATING PDF DOSSIER")
        bot.send_chat_action(call.message.chat.id, 'upload_document')
        
        try:
            pdf_path = generate_pdf_dossier(qr_code)
            if pdf_path and os.path.exists(pdf_path):
                with open(pdf_path, 'rb') as f:
                    bot.send_document(call.message.chat.id, f, caption=f"[DOC] Attendance Dossier")
                os.remove(pdf_path)
            else:
                bot.send_message(call.message.chat.id, "[X] Failed to generate PDF.")
        except Exception as e:
            bot.send_message(call.message.chat.id, f"[X] Error: {e}")
        finally:
            if loading_id: bot.delete_message(call.message.chat.id, loading_id)

    @bot.callback_query_handler(func=lambda call: call.data.startswith('ann_'))
    def handle_announcement_confirm(call):
        _, chat_id, ADMIN_ID, _, _ = get_settings()
        if str(call.from_user.id) != str(ADMIN_ID).strip():
            bot.answer_callback_query(call.id, "Unauthorized.")
            return
            
        action = call.data.split('_')[1]
        
        with user_states_lock:
            state = user_states.get(call.from_user.id)
            if not state:
                bot.answer_callback_query(call.id, "Session expired.")
                return

            if action == 'confirm':
                msg_ids = state.get('msg_ids', [])
                draft_id = state.get('draft_msg_id')
                if msg_ids:
                    # Broadcasting Animation
                    bot.edit_message_text("[UP] <b>BROADCASTING...</b>\n<code>[░░░░░░░░░░] 0%</code>", chat_id=call.message.chat.id, message_id=draft_id, parse_mode='HTML')
                    
                    try:
                        step = 100 / len(msg_ids)
                        for i, mid in enumerate(msg_ids, 1):
                            bot.copy_message(chat_id, call.message.chat.id, mid)
                            # Update progress
                            progress = int(i * step)
                            filled = int(progress / 10)
                            bar = "█" * filled + "░" * (10 - filled)
                            bot.edit_message_text(f"[UP] <b>BROADCASTING...</b>\n<code>[{bar}] {progress}%</code>", chat_id=call.message.chat.id, message_id=draft_id, parse_mode='HTML')
                            time.sleep(0.5)
                        
                        bot.edit_message_text("[OK] <b>Broadcast Successful!</b>\nAll items delivered to the group.", chat_id=call.message.chat.id, message_id=draft_id, parse_mode='HTML')
                        time.sleep(2)
                        bot.delete_message(call.message.chat.id, draft_id)
                        bot.send_message(call.message.chat.id, "Main menu restored.", reply_markup=get_admin_main_keyboard())
                    except Exception as e:
                        bot.edit_message_text(f"[X] <b>Broadcast Failed:</b> {e}", chat_id=call.message.chat.id, message_id=draft_id, parse_mode='HTML')
                else:
                    bot.answer_callback_query(call.id, "No items to send.")
            else:
                draft_id = state.get('draft_msg_id')
                if draft_id: bot.delete_message(call.message.chat.id, draft_id)
                bot.send_message(call.message.chat.id, "[X] Announcement discarded.", reply_markup=get_admin_main_keyboard())
            
            # Cleanup timer and reset state
            if state.get('timer'):
                state['timer'].cancel()
            user_states[call.from_user.id] = {'state': 'idle'}
            
        bot.answer_callback_query(call.id)

    @bot.callback_query_handler(func=lambda call: call.data.startswith('rec_'))
    def handle_recording_callbacks(call):
        _, _, ADMIN_ID, _, _ = get_settings()
        if str(call.from_user.id) != str(ADMIN_ID).strip():
            bot.answer_callback_query(call.id, "Unauthorized.")
            return
            
        state_data = user_states.get(call.from_user.id)
        if not state_data or state_data.get('frame_msg_id') != call.message.message_id:
            if call.data in ['rec_mode_daily', 'rec_mode_subject']:
                user_states[call.from_user.id] = {'state': 'recording_mode_select', 'frame_msg_id': call.message.message_id}
                state_data = user_states[call.from_user.id]
            else:
                bot.answer_callback_query(call.id, "Session expired or invalid message.")
                return
                
        action = call.data
        
        if action == 'rec_cancel':
            bot.edit_message_text(
                "<b>Recording Cancelled.</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nThe recording process was terminated.",
                chat_id=call.message.chat.id,
                message_id=call.message.message_id,
                parse_mode='HTML'
            )
            with user_states_lock:
                user_states[call.from_user.id] = {'state': 'idle'}
            bot.answer_callback_query(call.id)
            return

        if action == 'rec_mode_daily':
            state_data['recording_type'] = 'daily'
            show_date_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return
            
        if action == 'rec_mode_subject':
            state_data['recording_type'] = 'subject'
            show_subject_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return
            
        if action.startswith('rec_subsel_'):
            sub_id = int(action.split('_')[2])
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute("SELECT name FROM subjects WHERE id = ? LIMIT 1", (sub_id,))
            row = cursor.fetchone()
            conn.close()
            
            if row:
                state_data['subject_id'] = sub_id
                state_data['subject_name'] = row[0]
                show_date_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return
            
        if action == 'rec_back_mode':
            state_data['state'] = 'recording_mode_select'
            markup = InlineKeyboardMarkup()
            markup.row(InlineKeyboardButton("Daily Attendance", callback_data="rec_mode_daily"),
                       InlineKeyboardButton("Subject Attendance", callback_data="rec_mode_subject"))
            markup.row(InlineKeyboardButton("Cancel", callback_data="rec_cancel"))
            bot.edit_message_text(
                "<b>RECORD ATTENDANCE</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\n\nSelect the type of attendance you wish to record:",
                chat_id=call.message.chat.id,
                message_id=call.message.message_id,
                reply_markup=markup,
                parse_mode='HTML'
            )
            bot.answer_callback_query(call.id)
            return
            
        if action == 'rec_back_subjects':
            show_subject_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return
            
        if action == 'rec_back_dates':
            show_date_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return
            
        if action == 'rec_date_today':
            state_data['date'] = datetime.now().strftime("%Y-%m-%d")
            state_data['current_page'] = 0
            show_student_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return

        if action == 'rec_date_custom':
            show_custom_date_buttons_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return

        if action.startswith('rec_dateval_'):
            date_val = action.split('_', 2)[2]
            state_data['date'] = date_val
            state_data['current_page'] = 0
            show_student_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return

        if action == 'rec_page_prev':
            state_data['current_page'] = state_data.get('current_page', 0) - 1
            show_student_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return

        if action == 'rec_page_next':
            state_data['current_page'] = state_data.get('current_page', 0) + 1
            show_student_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return

        if action == 'rec_noop':
            bot.answer_callback_query(call.id)
            return
            
        if action == 'rec_back_student_select':
            show_student_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return

        if action.startswith('rec_stusel_'):
            qr_code = action.split('_', 2)[2]
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute("SELECT qr_code, name, course, student_type FROM users WHERE qr_code = ? LIMIT 1", (qr_code,))
            row = cursor.fetchone()
            conn.close()

            if row:
                state_data['student_qr'] = row[0]
                state_data['student_name'] = row[1]
                state_data['student_course'] = row[2]
                state_data['student_type'] = row[3]
                
                if state_data['recording_type'] == 'subject' and state_data.get('student_type') == 'irregular':
                    conn = sqlite3.connect(DB_PATH)
                    cursor = conn.cursor()
                    cursor.execute("SELECT 1 FROM student_subjects WHERE qr_code = ? AND subject_id = ?", 
                                   (state_data['student_qr'], state_data['subject_id']))
                    enrolled = cursor.fetchone()
                    conn.close()

                    if not enrolled:
                        markup = InlineKeyboardMarkup()
                        markup.row(InlineKeyboardButton("Back", callback_data="rec_back_student_select"),
                                   InlineKeyboardButton("Cancel", callback_data="rec_cancel"))
                        bot.edit_message_text(
                            f"<b>Enrollment Restriction</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\n"
                            f"Student: <b>{state_data['student_name']}</b> is irregular and NOT enrolled in "
                            f"<b>{state_data['subject_name']}</b>.\n\nRecording is blocked.",
                            chat_id=call.message.chat.id,
                            message_id=call.message.message_id,
                            reply_markup=markup,
                            parse_mode='HTML'
                        )
                        bot.answer_callback_query(call.id)
                        return
                
                show_status_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return

        if action.startswith('rec_status_'):
            status = action.split('_')[2]
            
            try:
                conn = sqlite3.connect(DB_PATH)
                cursor = conn.cursor()
                
                recording_type = state_data['recording_type']
                student_qr = state_data['student_qr']
                date_val = state_data['date']
                
                if recording_type == 'subject':
                    subject_id = state_data['subject_id']
                    cursor.execute("SELECT id FROM subject_attendance WHERE subject_id = ? AND qr_code = ? AND date = ?", 
                                   (subject_id, student_qr, date_val))
                    existing = cursor.fetchone()
                    time_now = datetime.now().strftime("%H:%M:%S")
                    
                    if existing:
                        cursor.execute("UPDATE subject_attendance SET status = ?, time = ?, recorded_at = CURRENT_TIMESTAMP WHERE id = ?",
                                       (status, time_now, existing[0]))
                    else:
                        cursor.execute("INSERT INTO subject_attendance (subject_id, qr_code, date, time, status) VALUES (?, ?, ?, ?, ?)",
                                       (subject_id, student_qr, date_val, time_now, status))
                else:
                    cursor.execute("SELECT active_school_year FROM settings LIMIT 1")
                    setting_row = cursor.fetchone()
                    active_sy = setting_row[0] if (setting_row and setting_row[0]) else "SY 2024-2025"
                    
                    cursor.execute("SELECT id FROM attendance WHERE qr_code = ? AND date = ?", 
                                   (student_qr, date_val))
                    existing = cursor.fetchone()
                    time_display = datetime.now().strftime("%I:%M %p")
                    
                    if existing:
                        if date_val == datetime.now().strftime("%Y-%m-%d"):
                            cursor.execute("UPDATE attendance SET status = ?, time = ? WHERE id = ?",
                                           (status, time_display, existing[0]))
                        else:
                            cursor.execute("UPDATE attendance SET status = ? WHERE id = ?",
                                           (status, existing[0]))
                    else:
                        cursor.execute("INSERT INTO attendance (qr_code, date, time, status, school_year) VALUES (?, ?, ?, ?, ?)",
                                       (student_qr, date_val, time_display, status, active_sy))
                
                conn.commit()
                conn.close()
                
                markup = InlineKeyboardMarkup()
                markup.row(InlineKeyboardButton("Record Another", callback_data="rec_another"),
                           InlineKeyboardButton("Finish", callback_data="rec_cancel"))
                
                context_name = "Daily Attendance" if recording_type == 'daily' else state_data['subject_name']
                msg_success = (
                    f"<b>Attendance Recorded Successfully</b>\n"
                    f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
                    f"Student: <b>{state_data['student_name']}</b>\n"
                    f"Context: <b>{context_name}</b>\n"
                    f"Date: <b>{date_val}</b>\n"
                    f"Status: <b>{status.capitalize()}</b>"
                )
                bot.edit_message_text(msg_success, chat_id=call.message.chat.id, message_id=call.message.message_id, reply_markup=markup, parse_mode='HTML')
                
            except Exception as e:
                bot.send_message(call.message.chat.id, f"Database Error: {e}")
                
            bot.answer_callback_query(call.id)
            return
            
        if action == 'rec_another':
            state_data.pop('student_qr', None)
            state_data.pop('student_name', None)
            state_data.pop('student_course', None)
            state_data.pop('student_type', None)
            
            show_student_select_screen(call.message.chat.id, call.message.message_id, state_data)
            bot.answer_callback_query(call.id)
            return

    @bot.message_handler(func=lambda message: not message.text.startswith('/'))
    def handle_text_interactions(message):
        """Routes text from buttons or search queries."""
        _, _, ADMIN_ID, _, _ = get_settings()
        is_admin = str(message.from_user.id) == str(ADMIN_ID).strip()
        state = user_states.get(message.from_user.id, {}).get('state', 'idle')
        
        text = message.text
        
        # Intercept manual typing during attendance recording flow
        if state.startswith('recording_'):
            try:
                bot.delete_message(message.chat.id, message.message_id)
            except:
                pass
            return
            
        # --- ADMIN ONLY / PRIVATE ONLY GATING ---
        if state.startswith('ordering_'):
            # Allow active order flows to continue (for students/admins)
            pass
        elif is_admin and message.chat.type == 'private':
            # Allow full bot features for admin in Private Chat
            pass
        else:
            # Silence for all other cases (GC or non-admin auto-replies)
            return

        # Handle Ordering Flow Inputs (Quantity/Name)
        if state.startswith('ordering_'):
            state_data = user_states.get(message.from_user.id)
            frame_id = state_data.get('frame_msg_id')
            
            # Auto-clean user spam: delete their input message
            try: bot.delete_message(message.chat.id, message.message_id)
            except: pass

            if state == 'ordering_qty':
                try:
                    qty = int(text)
                    if qty <= 0: raise ValueError()
                    
                    # Selective Even Check
                    is_even_only = state_data['selected_product'][5]
                    if is_even_only and qty % 2 != 0:
                        bot.edit_message_text(
                            f"[X] <b>Invalid Quantity</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nOrders for <b>{state_data['selected_product'][1]}</b> must be in <b>even numbers</b>.\n\nPlease type an even number (e.g. 10, 50, 100):",
                            chat_id=message.chat.id, message_id=frame_id,
                            reply_markup=InlineKeyboardMarkup().add(InlineKeyboardButton("[X] Abort", callback_data="ord_cancel"))
                        )
                        return
                    
                    # Stock Check
                    stock = state_data['selected_product'][3]
                    if qty > stock:
                        bot.edit_message_text(
                            f"[X] <b>Low Stock</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nRequested: {qty} pcs\nAvailable: <b>{stock} pcs</b>\n\nPlease enter a lower quantity:",
                            chat_id=message.chat.id, message_id=frame_id,
                            reply_markup=InlineKeyboardMarkup().add(InlineKeyboardButton("[X] Abort", callback_data="ord_cancel"))
                        )
                        return
                    
                    state_data['quantity'] = qty
                    state_data['total_price'] = qty * state_data['selected_product'][2]
                    state_data['state'] = 'ordering_name'
                    
                    bot.edit_message_text(
                        f"[CART] <b>ORDERING: {state_data['selected_product'][1]}</b>\n"
                        f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
                        f"Quantity: <b>{qty} pcs</b>\n"
                        f"Total: <b>₱{state_data['total_price']}</b>\n\n"
                        f"<b>STEP: Full Name</b>\n"
                        f"Please type your full name for the record:",
                        chat_id=message.chat.id, message_id=frame_id,
                        reply_markup=InlineKeyboardMarkup().add(InlineKeyboardButton("[X] Abort", callback_data="ord_cancel"))
                    )
                except ValueError:
                    bot.edit_message_text(
                        "[X] <b>Invalid Input</b>\nPlease enter a valid whole number for quantity:",
                        chat_id=message.chat.id, message_id=frame_id,
                        reply_markup=InlineKeyboardMarkup().add(InlineKeyboardButton("[X] Abort", callback_data="ord_cancel"))
                    )
                return

            if state == 'ordering_name':
                state_data['customer_name'] = text
                state_data['state'] = 'ordering_confirm'
                
                p_name = state_data['selected_product'][1]
                qty = state_data['quantity']
                total = state_data['total_price']
                
                msg = (
                    f"[EDIT] <b>VERIFY ORDER SUMMARY</b>\n"
                    f"━━━━━━━━━━━━━━━━━━━━┳═─\n"
                    f"<b>Product:</b> {p_name}\n"
                    f"<b>Quantity:</b> {qty} pcs\n"
                    f"<b>Total:</b> ₱{total}\n"
                    f"<b>Customer:</b> {text}\n\n"
                    f"Ready to finalize this order?"
                )
                
                markup = InlineKeyboardMarkup()
                markup.row(InlineKeyboardButton("[OK] Confirm Order", callback_data="ord_confirm"), 
                          InlineKeyboardButton("[X] Discard", callback_data="ord_cancel"))
                
                bot.edit_message_text(msg, chat_id=message.chat.id, message_id=frame_id, reply_markup=markup)
                return

        if is_admin and state == 'announcing':
            # Handle text announcement with buffering and confirmation delay
            with user_states_lock:
                state_data = user_states[message.from_user.id]
                state_data['msg_ids'].append(message.message_id)
                count = len(state_data['msg_ids'])
                draft_id = state_data.get('draft_msg_id')
                
                # Update Draft UI immediately
                try:
                    markup = InlineKeyboardMarkup()
                    markup.row(InlineKeyboardButton("[OK] Broadcast Now", callback_data="ann_confirm"), 
                              InlineKeyboardButton("[X] Discard", callback_data="ann_cancel"))
                    bot.edit_message_text(f"[ANNOUNCE] <b>ANNOUNCEMENT DRAFT</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nStatus: <b>Buffering Input...</b>\nItems: <b>[{count}]</b>\n\n<i>Sending more items? I'm listening...</i>", chat_id=message.chat.id, message_id=draft_id, parse_mode='HTML', reply_markup=markup)
                except: pass

                if state_data.get('timer'):
                    state_data['timer'].cancel()
                
                # Wait 1.5s for more text or media before asking for final verification
                state_data['timer'] = threading.Timer(1.5, trigger_announcement_confirmation, args=(message.from_user.id, message.chat.id, "text"))
                state_data['timer'].start()
            return

        # Main Interface Button routing (Admins only, Private only)
        if text == "Search Student":
            bot.reply_to(message, "<b>Search</b>\nType the student name or ID to search.")
        elif text == "Record Attendance":
            handle_record_attendance(message)
        elif text == "Today's Stats":
            handle_today(message)
        elif text == "Announce":
            handle_announce_command(message)
        elif text == "Export CSV":
            handle_export(message)
        elif text == "All Dossiers":
            handle_dossier_all(message)
        elif text == "Get Database":
            handle_getdb(message)
        else:
            # Fallback to auto-search
            handle_search(message)

    @bot.message_handler(content_types=['photo', 'video', 'voice', 'audio'])
    def handle_media_announcement(message):
        _, _, ADMIN_ID, _, _ = get_settings()
        if str(message.from_user.id) != str(ADMIN_ID).strip():
            return
            
        state = user_states.get(message.from_user.id, {}).get('state', 'idle')
        if state == 'announcing':
            # Handle media announcement with buffering and confirmation delay
            with user_states_lock:
                state_data = user_states[message.from_user.id]
                state_data['msg_ids'].append(message.message_id)
                count = len(state_data['msg_ids'])
                draft_id = state_data.get('draft_msg_id')
                
                # Update Draft UI immediately
                try:
                    markup = InlineKeyboardMarkup()
                    markup.row(InlineKeyboardButton("[OK] Broadcast Now", callback_data="ann_confirm"), 
                              InlineKeyboardButton("[X] Discard", callback_data="ann_cancel"))
                    bot.edit_message_text(f"[ANNOUNCE] <b>ANNOUNCEMENT DRAFT</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nStatus: <b>Receiving Media...</b>\nItems: <b>[{count}]</b>\n\n<i>Processing your file(s)...</i>", chat_id=message.chat.id, message_id=draft_id, parse_mode='HTML', reply_markup=markup)
                except: pass

                if state_data.get('timer'):
                    state_data['timer'].cancel()
                
                # Wait 2.0s (buffering for media groups/albums) before asking for confirmation
                state_data['timer'] = threading.Timer(2.0, trigger_announcement_confirmation, args=(message.from_user.id, message.chat.id, message.content_type))
                state_data['timer'].start()

    @bot.message_handler(commands=['getdb'])
    def handle_getdb(message):
        _, _, ADMIN_ID, _, _ = get_settings()
        if not ADMIN_ID or str(message.from_user.id) != str(ADMIN_ID).strip() or message.chat.type != 'private':
            bot.reply_to(message, "[X] Unauthorized or invalid chat type.")
            return
        
        if os.path.exists(DB_PATH):
            with open(DB_PATH, 'rb') as db_file:
                bot.send_document(message.chat.id, db_file, caption="[FILE] Here is the current attendance database.")
        else:
            bot.reply_to(message, "[X] Database file not found.")

    @bot.message_handler(content_types=['document'])
    def handle_document(message):
        _, _, ADMIN_ID, _, _ = get_settings()
        if not ADMIN_ID or str(message.from_user.id) != str(ADMIN_ID).strip():
            return
            
        state = user_states.get(message.from_user.id, {}).get('state', 'idle')
        
        # Priority: Announcement mode
        if state == 'announcing':
            # Handle document announcement with buffering and confirmation delay
            with user_states_lock:
                state_data = user_states[message.from_user.id]
                state_data['msg_ids'].append(message.message_id)
                count = len(state_data['msg_ids'])
                draft_id = state_data.get('draft_msg_id')
                
                # Update Draft UI immediately
                try:
                    markup = InlineKeyboardMarkup()
                    markup.row(InlineKeyboardButton("[OK] Broadcast Now", callback_data="ann_confirm"), 
                              InlineKeyboardButton("[X] Discard", callback_data="ann_cancel"))
                    bot.edit_message_text(f"[ANNOUNCE] <b>ANNOUNCEMENT DRAFT</b>\n━━━━━━━━━━━━━━━━━━━━┳═─\nStatus: <b>File Ingested</b>\nItems: <b>[{count}]</b>\n\n<i>Waiting for more or confirm below.</i>", chat_id=message.chat.id, message_id=draft_id, parse_mode='HTML', reply_markup=markup)
                except: pass

                if state_data.get('timer'):
                    state_data['timer'].cancel()
                
                # Wait 2.0s for potentially multiple files
                state_data['timer'] = threading.Timer(2.0, trigger_announcement_confirmation, args=(message.from_user.id, message.chat.id, "document"))
                state_data['timer'].start()
            return

        # Fallback: Database Sync
        if message.document.file_name.endswith('.db') or message.document.file_name.endswith('.sqlite'):
            try:
                msg = bot.reply_to(message, "[WAIT] Downloading and syncing database...")
                file_info = bot.get_file(message.document.file_id)
                downloaded_file = bot.download_file(file_info.file_path)
                
                # Create backup
                backup_dir = os.path.dirname(DB_PATH).replace('database', 'backups')
                if not os.path.exists(backup_dir):
                    os.makedirs(backup_dir)
                    
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                backup_path = os.path.join(backup_dir, f"attendance_backup_{timestamp}.db")
                
                if os.path.exists(DB_PATH):
                    shutil.copy2(DB_PATH, backup_path)
                    
                # Save new DB
                with open(DB_PATH, 'wb') as new_file:
                    new_file.write(downloaded_file)
                    
                bot.edit_message_text(f"[OK] Database synchronized successfully!\nPrevious database backed up as: `{os.path.basename(backup_path)}`", chat_id=msg.chat.id, message_id=msg.message_id, parse_mode='Markdown')
            except Exception as e:
                bot.reply_to(message, f"[X] Failed to sync: {e}")

    if __name__ == "__main__":
        # Re-use existing threads if already running
        global threads_started
        if 'threads_started' not in globals():
            threads_started = False

        if not threads_started:
            # Start Background Thread for Queue
            threading.Thread(target=queue_worker, daemon=True).start()
            
            # Start Background Thread for Birthdays
            threading.Thread(target=birthday_check_worker, daemon=True).start()
            threads_started = True
        
        try:
            me = bot.get_me()
            print(f"Bot fully operational and polling (https://t.me/{me.username})")
            bot.polling(none_stop=True, timeout=60)
        except telebot.apihelper.ApiTelegramException as e:
            if e.error_code == 409:
                print("\n[X] 409 CONFLICT ERROR:")
                print("Another instance of this bot is already running!")
                print("Please close any other hidden terminal windows or scripts running the bot.")
            else:
                print(f"Telegram API Error: {e}")
            time.sleep(5)
        except Exception as e:
            print(f"Bot crashed or connection lost: {e}")
            time.sleep(5)
