<?php
// api/export_billing.php
ob_start();
date_default_timezone_set("Asia/Manila");
require "../includes/db.php";

// Suppress errors
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
ini_set('display_errors', 0);

$filename = "Ambagan_Report_" . date('Y-m-d') . ".xls";

// Get Settings for Quota/Fixed info
$sStmt = $pdo->query("SELECT * FROM settings LIMIT 1");
$settings = $sStmt->fetch(PDO::FETCH_ASSOC);
$quota = floatval($settings['billing_quota'] ?? 50);
$mode = $settings['billing_mode'] ?? 'fixed';

try {
    // Fetch All Students + Payment status
    // Use LEFT JOIN to show unpaid students too
    $sql = "SELECT 
                u.name, 
                b.amount, 
                b.payment_date
            FROM users u
            LEFT JOIN billing b ON u.qr_code = b.qr_code
            ORDER BY u.name ASC";
    
    $records = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);

    // Calc Stats
    $totalStudents = count($records);
    $totalCollected = 0;
    $paidCount = 0;

    foreach ($records as $r) {
        if (!empty($r['amount'])) {
            $totalCollected += $r['amount'];
            $paidCount++;
        }
    }
    
    $unpaidCount = $totalStudents - $paidCount;

} catch (PDOException $e) {
    ob_clean();
    die("Database Logic Error");
}

// Output Headers
while (ob_get_level()) ob_end_clean();

header("Content-Type: application/vnd.ms-excel; charset=UTF-8");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; font-size: 11pt; }
        table { border-collapse: collapse; width: 100%; }
        td, th { border: 1px solid #000; padding: 6px 10px; vertical-align: middle; }
        .no-border { border: none !important; }
        
        /* Styles matching export.php */
        .title-row { background-color: #15803d; color: #fff; font-size: 16pt; font-weight: bold; text-align: center; height: 40px; }
        .date-row { background-color: #f0fdf4; color: #166534; font-size: 12pt; font-weight: bold; text-align: center; }
        
        .stat-label { background-color: #f1f5f9; font-weight: bold; text-align: center; }
        .stat-val { font-size: 12pt; font-weight: bold; text-align: center; }
        
        .header-col { background-color: #e2e8f0; font-weight: bold; text-align: left; }
        .center { text-align: center; }
        
        .c-green { color: #166534; font-weight: bold; }
        .c-red { color: #dc2626; font-weight: bold; }
    </style>
</head>
<body>
    <table>
        <!-- Title -->
        <tr><td colspan="4" class="title-row">AMBAGAN (CONTRIBUTION) REPORT</td></tr>
        <tr><td colspan="4" class="date-row">Generated: <?= date('F j, Y h:i A') ?></td></tr>
        
        <tr><td colspan="4" class="no-border"></td></tr>

        <!-- Summary -->
        <tr>
            <td class="stat-label">TOTAL STUDENTS</td>
            <td class="stat-label">COLLECTED</td>
            <td class="stat-label">TARGET (<?= strtoupper($mode) ?>)</td>
            <td class="stat-label">PAID / UNPAID</td>
        </tr>
        <tr>
            <td class="stat-val"><?= $totalStudents ?></td>
            <td class="stat-val c-green">₱<?= number_format($totalCollected, 2) ?></td>
            <td class="stat-val">₱<?= number_format($quota, 2) ?></td>
            <td class="stat-val"><?= $paidCount ?> / <?= $unpaidCount ?></td>
        </tr>

        <tr><td colspan="4" class="no-border"></td></tr>

        <!-- Data -->
        <tr>
            <th class="header-col" width="50">#</th>
            <th class="header-col" width="250">STUDENT NAME</th>
            <th class="header-col center" width="150">AMOUNT PAID</th>
            <th class="header-col center" width="150">DATE PAID</th>
        </tr>

        <?php foreach($records as $idx => $row): 
            $isPaid = !empty($row['payment_date']);
            $amt = $isPaid ? '₱' . number_format($row['amount'], 2) : '-';
            $date = $isPaid ? date('M j, Y h:i A', strtotime($row['payment_date'])) : '-';
        ?>
        <tr>
            <td class="center"><?= $idx + 1 ?></td>
            <td><?= htmlspecialchars($row['name']) ?></td>
            <td class="center <?= $isPaid ? 'c-green' : 'c-red' ?>"><?= $amt ?></td>
            <td class="center"><?= $date ?></td>
        </tr>
        <?php endforeach; ?>
    </table>

    <table>
        <tr><td colspan="4" class="no-border center" style="color: #94a3b8; font-size: 9pt; padding-top: 20px;">Generated by MCK</td></tr>
    </table>

</body>
</html>
